---
# yamllint disable rule:line-length
format: 1
modbuild:
  defaults:
    group: Tools
    overlay: base
    relstage: unstable
    compile_in_sourcetree: true
    urls:
      - url: https://github.com/Pmodules/$P/archive/refs/tags/$P-${V_PKG}.tar.gz
  shasums:
  versions:
    2.1.3:
      config:
        relstage: unstable
        docfiles: [LICENSE.txt]
        sub_packages:
          - name: sevenz
            version: !!str 26.01
          - name: yq
            version: 4.53.2
          - name: bash
            version: 5.3.9
          - name: patchelf
            version: 0.14.5

bash:
  type: sub_package
  defaults:
  shasums:
    bash-5.3.tar.gz: 0d5cd86965f869a26cf64f4b71be7b96f90a3ba8b3d74e27e8e9d9d5550f31ba 
  versions:
    5.3.9:
      config:
        urls:
          - url: https://ftp.gnu.org/gnu/bash/bash-5.3.tar.gz
          - patch_file: files/bash53-001
          - patch_file: files/bash53-002
          - patch_file: files/bash53-003
          - patch_file: files/bash53-004
          - patch_file: files/bash53-005
          - patch_file: files/bash53-006
          - patch_file: files/bash53-007
          - patch_file: files/bash53-008
          - patch_file: files/bash53-009
        configure_args:
          - --bindir=${PREFIX}/libexec
yq:
  type: sub_package
  shasums:
  versions:
    4.53.2:
      variants:
        - target_cpus:
            - x86_64
          urls:
            - url: https://github.com/mikefarah/yq/releases/download/v4.53.2/yq_linux_amd64.tar.gz
              unpack_dir: ${SRC_DIR}

sevenz:
  type: sub_package
  defaults:
  shasums:
    7zip-26.01.tar.gz: f4212b508641b3584f7089ab67bc0aba028c631f049b4dd603ff07853e72e749
  versions:
    26.01:
      config:
        urls:
          - url: https://github.com/ip7z/7zip/archive/refs/tags/${V_PKG}.tar.gz
            name: 7zip-${V_PKG}.tar.gz

patchelf:
  type: sub_package
  defaults:
    urls:
      - url: https://github.com/NixOS/$P/archive/${V_PKG}.tar.gz
        name: $P-${V_PKG}.tar.gz
    configure_args:
      - --bindir=${PREFIX}/libexec
    compile_in_sourcetree: true
  versions:
    0.14.5:
