= *BUILDING MODULES*

== Introduction

In the simplest case adding a module can be done by adding a modulefile to a certain directory. Below is an example of a "do nothing" modulefile.

.Example: `null/1.0.0`
[source,sh]
----
#%Pmodule

module-whatis           "does absolutely nothing"
module-maintainer       "Achim Gsell <achim.gsell@psi.ch>"
module-license          "MIT"

module-help     "
This is a do nothing module.
"
----

Modulefiles are written in the Tool Command Language (Tcl). 

In principal, it is possible to install modules 'by hand' by installing the software and modulefiles at the right place. For reproducibility, documentation and re-usability it is highly recommended to write build-recipes for each module or - at least - a README.md and host everything on a Gitforge (gitea.psi.ch, github.com, gitlab.com ...).

== Predefined variables 

*In modulefiles and build-scripts the following variables are predefined:*

`P`:: the name of the module
`V`:: the module version. The version number consists of a major- and a minor version number, a patch-level and a release number. All numbers but the major version number are optional. Major-, minor number and patch-level are separated by dots, the release number by a minus. Example: `1.0.3-2`
`V_MAJOR`:: the major version number. Example: `1`
`V_MINOR`:: the minor version number. Example: `0`
`V_PATCHLVL`:: the patch-level. Example: `3`
`V_RELEASE`:: the release number. Example: `2`
`V_PKG`:: version number without release.
`PREFIX`:: installation prefix of the module.

*In build-scripts the following variables are predefined too:*

`TEMP_DIR`:: directory for temporary files.
`SRC_DIR`:: directory of unpacked sources, set to `$PMODULES_TMPDIR/$P-$V/src`
`BUILD_DIR`:: build directory, set to `$PMODULES_TMPDIR/$P-$V/build`
`BUILDBLOCK_DIR`:: Directory where the build-script is in.
`BUILD_SCRIPT`:: Name of the build script.
`JOBS`:: Number of parallel `make` jobs.

[id="building-modules", reftext="Building Pmodules"]
== Building a module

Perform the following steps for a new module:

1. Create a directory with the name of the module.
2. Write the configuration file. See section <<writing-build-configuration-files>>.
3. Write the modulefile. See section <<sec-modulefiles>>.
4. Code all required steps to install a software in a script. If it is not possible to script everything, code as much as possible and document additional steps in a README file. See section <<writing-build-scripts>>.

The first - and sometimes also to most challenging - step in building a module from source is to learn how to download, configure, compile and install a software package and dependencies the package has. The next steps are writing a configuration file, a modulefile and a script to download, configure, compile and install it.  

In general the following steps needs to be performed:

prepare:: Download, unpack, apply patches (optional). Downloading the software might not be scriptable due to password protection or other measurements.  

configure:: (only for software distributed as source code) This step heavily depends on the software itself. In many cases autotools or CMake is used, in some cases you have to deal with Makefiles or other tools.   

build:: (only for software distributed as source code) compile/build everything

install:: Install everything in the target directory. In case of a binary package this might not be scriptable.

[id="writing-build-configuration-files", reftext="Writing build configuration files"]
== Writing build configuration files
include::Building_Pmodules/build-config-files/config_yaml.adoc[leveloffset=+2]

---

[id="writing-build-scripts", reftext="Writing build scripts"]
== Writing build scripts

Pmodules has it's own 'interpreter' to run build-scripts written in Bash. The name of the interpreter is `modbuild`. Thus the first line (the so called 'shebang') of a build-script must be
[source,sh]
----
#!/usr/bin/env modbuild
----
As already mentioned the four steps 'prepare', 'configure', 'build' and 'install' has to be performed to build a Pmodule. These steps maps to the functions:

prepare::
    `pbuild::pre_prep()` +
    `pbuild::prep()` +
    `pbuild::post_prep()`
configure::
    `pbuild::pre_configure()` +
    `pbuild::configure()` +
    `pbuild::post_configure()`
compile::
    `pbuild::pre_compile()` +
    `pbuild::compile()` +
    `pbuild::post_compile()`
install::
    `pbuild::pre_install()` +
    `pbuild::install()` +
    `pbuild::post_install()`

In many cases you don't have to implement the the functions `pbuild::prep()`, `pbuild::configure()`, `pbuild::compile()` and `pbuild::install()` or at least not all of them. The build-system provides default implementations for these functions. In the simplest case, the build script consists only of the shebang line (only for Pmodules >= 1.1). In this case all further information for building the module is in the configuration file. For software that uses autotools or CMake for configuration and creation of Makefiles, the standard functions can practically always be used. The functions `pbuild::pre_STEP` and `pbuild::post_STEP` can be used to hook into each step before and after the default function has been called. For example `pbuild::pre_configure()` can be used to set arguments for autotools or CMake as in the build-script for Gnuplot:


=== Overloading the default implementations

If the build-system of the software package isn't autotools or CMake you have to overload the default implementation of `pbuild::configure`. 
[source,sh]
----
pbuild::configure(){
        # add code to configure the software package
}
----
In case where no configuration is required, overload the default function with
[source,sh]
----
pbuild::configure(){
        : # do nothing
}
----
You can do the same with the other default implementation.

=== Modules from binary packages

If you have a binary package like Matlab, Mathematica, ANSYS, it might not be possible to script the installation. In this case you should use a dummy build-script like below and document the installation in a `README.md`:
[source,sh]
----
#!/usr/bin/env modbuild

pbuild::prep() { :; }
pbuild::configure() { :; }
pbuild::compile() { :; }
pbuild::install() { :; }
----
If the installation can be scripted, code this in the function `pbuild::install`.
[source,sh]
----
#!/usr/bin/env modbuild

pbuild::prep() { :; }
pbuild::configure() { :; }
pbuild::compile() { :; }
pbuild::install() {
        # add code to call the installer here
}
----

=== Functions to compare versions
include::Building_Pmodules/functions/cmp_versions.adoc[leveloffset=+3]

=== Build functions
include::Building_Pmodules/functions/prep.adoc[leveloffset=+3]
---
include::Building_Pmodules/functions/configure.adoc[leveloffset=+3]
---
include::Building_Pmodules/functions/compile.adoc[leveloffset=+3]
---
include::Building_Pmodules/functions/install.adoc[leveloffset=+3]

[leveloffset=+1]

